// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcG1_-9kFRxGDCJpd1Jt8vPKpXdJEEbHg',
    appId: '1:833739694425:web:f8289f72cb5dc02059ec48',
    messagingSenderId: '833739694425',
    projectId: 'isitek-d2d9a',
    authDomain: 'isitek-d2d9a.firebaseapp.com',
    storageBucket: 'isitek-d2d9a.firebasestorage.app',
    measurementId: 'G-Q3Z0SBMZGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk3c7YrSqbaiLIK55T77MXUbpSguYhkp4',
    appId: '1:833739694425:android:24513a39d87511db59ec48',
    messagingSenderId: '833739694425',
    projectId: 'isitek-d2d9a',
    storageBucket: 'isitek-d2d9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTanhBkp2F-FyLH8GfbPRrkjquAW29zMk',
    appId: '1:833739694425:ios:3f185238e2002a9859ec48',
    messagingSenderId: '833739694425',
    projectId: 'isitek-d2d9a',
    storageBucket: 'isitek-d2d9a.firebasestorage.app',
    iosBundleId: 'com.example.isitekProNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTanhBkp2F-FyLH8GfbPRrkjquAW29zMk',
    appId: '1:833739694425:ios:3f185238e2002a9859ec48',
    messagingSenderId: '833739694425',
    projectId: 'isitek-d2d9a',
    storageBucket: 'isitek-d2d9a.firebasestorage.app',
    iosBundleId: 'com.example.isitekProNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcG1_-9kFRxGDCJpd1Jt8vPKpXdJEEbHg',
    appId: '1:833739694425:web:9c20459564e497b359ec48',
    messagingSenderId: '833739694425',
    projectId: 'isitek-d2d9a',
    authDomain: 'isitek-d2d9a.firebaseapp.com',
    storageBucket: 'isitek-d2d9a.firebasestorage.app',
    measurementId: 'G-W804V7DHXV',
  );
}
